Standardise content max-width to match DFE Frontend
DFE-Digital/record-concerns-support-trusts pull request #1211
Opened 2024-05-17 09:29 UTC by DrizzlyOwl

**What is the change?**
Sets the correct content width for shared and generic page layouts to `1200px`

**Why do we need the change?**
The DFE Header is 1200px but the footer and page layouts are still using the govuk page width which is 960px. This makes the page look a little odd as the header is far wider than the rest of the page elements.

**What is the impact?**
No impact, only HTML classes have changed.

**Azure DevOps Ticket**
N/A

2024-05-17 09:31 UTC, DrizzlyOwl commented on ConcernsCaseWork/ConcernsCaseWork/Pages/Error.cshtml
> +        <div class="govuk-grid-column-two-thirds-from-desktop">
This template was missing the column HTML node so the content was breaking out of the grid

2024-05-17 14:47 UTC, mikestock-nimble approved these changes

2024-05-17 14:49 UTC, mikestock-nimble requested changes
I think there are some pages that haven't had this applied, will take a look

2024-05-21 08:31 UTC, closed without merging

2024-05-21 08:31 UTC, mikestock-nimble commented
superseded by:

https://github.com/DFE-Digital/record-concerns-support-trusts/pull/1213